;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]

; Polar Night
background-0 = #2E3440
background-1 = #3B4252
background-2 = #434C5E
background-3 = #4C566A

;Snow Storm
snow-0 		 = #D8DEE9
snow-1 		 = #E5E9F0
snow-2 		 = #ECEFF4

;Frost
frost-1 	 = #8FBCBB
frost-2 	 = #88C0D0
frost-3 	 = #81A1C1
frost-4 	 = #5E81AC

;Everforest
red-0 		 = #E67E80
orange-0 	 = #E69875
yellow-0 	 = #DBBC7F
green-0 	 = #A7C080
blue-0 		 = #7FBBB3
aqua-0 		 = #83C092
purple-0 	 = #D699B6

;Aurora
red-1 		 = #BF616A
orange-1 	 = #D08770
yellow-1 	 = #EBCB8B
green-1 	 = #A3BE8C
purple-1 	 = #B48EAD

[bar/example]
width = 100%
height = 19pt
radius = 0

bottom = true

; dpi = 96

background = ${colors.background-1}
foreground = ${colors.snow-3}

line-size = 0pt

border-size = 0pt
border-top = 0pt
border-color = #00000000

padding-left = 0px
padding-right = 0px

module-margin = 0px

#separator = |
separator-foreground = ${colors.disabled}

font-0 = IosevkaTermNerdFont:weight=bold:size=11;3
font-1 = IosevkaNerdFont Mono:size=19;6
font-2 = IosevkaTermNerdFont Mono:weight=bold:size=11;3

modules-left = xworkspaces 
modules-right = filesystem memory xkeyboard pulseaudio battery wlan date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

icon-0 = 1;%{T2}%{F#e67380}󰊠%{F-}%{T-}
icon-1 = 2;%{T2}%{F#e69875}󰊠%{F-}%{T-}
icon-2 = 3;%{T2}%{F#dbbc7f}󰊠%{F-}%{T-}
icon-3 = 4;%{T2}%{F#a7c080}󰊠%{F-}%{T-}
icon-4 = 5;%{T2}%{F#7fbbb3}󰊠%{F-}%{T-}
icon-5 = 6;%{T2}%{F#83c092}󰊠%{F-}%{T-}
icon-6 = 7;%{T2}%{F#d699b6}󰊠%{F-}%{T-}
icon-7 = 8;%{T2}%{F#e67e80}󰊠%{F-}%{T-}
icon-8 = 9;%{T2}%{F#e69875}󰊠%{F-}%{T-}
icon-9 = 10;%{T2}%{F#7fbbb3}󰊠%{F-}%{T-}

label-active = %{T2}󰮯%{T-}
label-active-foreground = #ebcb8b
label-active-background = ${colors.background-3}
label-active-underline= ${colors.primary}
label-active-padding-left = 12px
label-active-padding-right = 12px

label-occupied = %icon%
label-occupied-padding-left = 12px
label-occupied-padding-right = 12px
label-occupied-background = ${colors.background-2}

label-urgent = %{T2}󰊠%{T-}
label-urgent-background = ${colors.alert}
label-urgent-padding = 12px

label-empty = %{T2}%{T-}
label-empty-foreground = ${colors.disabled}
label-empty-padding = 12px

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

format-mounted = <label-mounted>
format-unmounted = <label-unmounted>

label-mounted = 󱛟  %percentage_used%%
label-mounted-background = ${colors.frost-1}
label-mounted-padding-left = 8px
label-mounted-padding-right = 8px

label-unmounted = %mountpoint% not mounted
label-unmounted-padding-left = 8px
label-unmounted-padding-right = 8px

[module/pulseaudio]
type = internal/pulseaudio

format-volume-background = ${colors.frost-4}

format-volume-prefix = "󰕾 "
format-volume = <label-volume>

format-muted-background = ${colors.orange-1}

format-muted-prefix = "󰖁 "

label-volume = %percentage%%
label-volume-padding-left = 4px
label-volume-padding-right = 8px

label-muted = muted
label-muted-padding-left = 4px
label-muted-padding-right = 8px

format-volume-prefix-padding-left = 8px
#format-volume-prefix-padding-right= 4px

format-muted-prefix-padding-left = 8px
#format-muted-prefix-padding-right= 4px

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format = <label-layout>

label-layout = %layout%
label-layout-padding-right = 8pt

format-background = ${colors.frost-3}
format-prefix = "󰌌  "
format-prefix-padding-left = 8px

[module/memory]
type = internal/memory
interval = 2

label = %percentage_used:2%%
label-padding-right= 8px

format = <label>
format-background = ${colors.frost-2}

format-prefix = "  "
format-prefix-padding-left = 9px

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#ebcb8b}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

#label-connected = %{F#A3BE8C}%{A1:nmcli radio wifi off:}󰤨 %{A}%{F-} %local_ip%
label-connected = %{A1:nmcli radio wifi off:}󰤨 %{A} %essid% %local_ip%
label-connected-background = ${colors.green-1}
label-connected-padding-left = 10px
label-connected-padding-right = 9px

label-disconnected = "%{T2}%{A1:nmcli radio wifi on:}%{A}%{T-}"
label-disconnected-background = ${colors.red-1}
label-disconnected-padding-left = 10px
label-disconnected-padding-right = 10px

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#ebcb8b}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

# date = 󰥔 %H:%M
date = %{T3}%H %M%{T-}
date-alt = %{T3}%Y-%m-%d%{T-} %{T3}%H %M %S%{T-}

label = %date%
label-foreground = ${colors.primary}
label-background = ${colors.purple-1}
label-padding-left = 4px
label-padding-right = 6px

format-prefix = "%{T1}󰥔 %{T-}"
format-prefix-background = ${colors.purple-1}
format-prefix-padding-left = 8px
format-prefix-padding-right = 0px

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 99
format-charging = <label-charging>
format-discharging = <label-discharging>
format-full= <label-full>
format-low= <label-low>

label-charging = 󰁹 %percentage%%
label-charging-background = ${colors.frost-1}
label-charging-padding-left = 8px
label-charging-padding-right = 8px

label-discharging = 󰁹 %percentage%%
label-discharging-background = ${colors.yellow-1}
label-discharging-padding-left = 8px
label-discharging-padding-right = 8px

label-full = 󰁹 %percentage%%
label-full-background = ${colors.green-1}
label-full-padding-left = 8px
label-full-padding-right = 8px

label-low = 󰁺 %percentage%%
label-low-background = ${colors.red-1}
label-low-padding-left = 8px
label-low-padding-right = 8px
; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 5

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; vim:ft=dosini
