backend = "glx";
corner-radius = 12;
shadow = true;

fading = true;
fade-in-step=0.03;
fade-out-step=0.03;
fade-delta=10;

shadow-exclude = [
   "class_g = 'Eww'",
   "window_type = 'menu'",
   "window_type = 'utility'",
   "window_type = 'popup_menu'",
   "class_g = 'Rofi'" 
]

rounded-corners-exclude = [
    "class_g = 'krita'"
]
