backend = "glx";
use-damage = false;
shadow = false;
corner-radius = 0;
fading = true;
fade-in-step = 0.01;
fade-out-step = 0.01;
fade-delta = 1;

shadow-exclude = [
	"class_g = 'Rofi'",
	"window_type = 'dnd'", 			#drag items
	"window_type = 'menu'", 		#Nautilus
	"window_type = 'dock'"
];

wintypes:
{
	popup_menu = {shadow = true; opacity = 1; full-shadow = false; }
	utility = {shadow = true; opacity = 1; full-shadow = false; }
	tooltip = {shadow = true; opacity = 1; full-shadow = false; }
	dnd = {shadow = false ; opacity = 0; full-shadow = false; }
};

